# Generated by Django 4.0.1 on 2022-02-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxymodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myexamcenter',
            options={'ordering': ['id']},
        ),
    ]
