# Generated by Django 4.0.1 on 2022-02-03 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_model_inheritance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contractor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
