# Generated by Django 4.0.1 on 2022-02-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
